[tool.poetry]
name = "voxcity"
version = "0.3.9"
description = "voxcity is an easy and one-stop tool to output 3d city models for microclimate simulation by integrating multiple geospatial open-data"
authors = ["Kunihiko Fujiwara <kunihiko@nus.edu.sg>"]
maintainers = ["Kunihiko Fujiwara <kunihiko@nus.edu.sg>"]
readme = "README.md"
license = "MIT"
packages = [
    { include = "voxcity", from = "src" }
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
typer = ">=0.9.0"
pandas = ">=2.0.0"
requests = ">=2.31.0"
pyproj = ">=3.6.1"
ipyleaflet = ">=0.17.0"
geopandas = ">=0.14.0"
rasterio = "1.3.11"
shapely = ">=2.0.0"
gdown = ">=5.0.0"
numpy = ">=1.26.0"
matplotlib = ">=3.8.0"
contextily = ">=1.4.0"
fiona = ">=1.9.5"
rtree = ">=1.0.0"
plotly = ">=5.18.0"
tqdm = ">=4.66.0"
scipy = ">=1.11.0"
affine = ">=2.4.0"
earthengine-api = ">=0.1.390"
geemap = ">=0.29.0"
rio-cogeo = ">=5.0.0"
geopy = ">=2.4.1"
py-vox-io = ">=0.1.0"
mapbox_vector_tile = ">=2.0.1"
numba = ">=0.58.0"
reverse_geocoder = ">=1.5.1"
pycountry = ">=23.12.0"
osm2geojson = ">=0.2.4"
seaborn = ">=0.13.0"
overturemaps = ">=0.1.0"
protobuf = "3.20.3"
timezonefinder = ">=6.5.0"
astral = ">=3.2.0"
osmnx = ">=1.9.0"
joblib = ">=1.3.2"

[tool.poetry.group.dev.dependencies]
coverage = ">=7.4.0"
mypy = ">=1.8.0"
pytest = ">=8.0.0"
ruff = ">=0.2.0"

[project.urls]
bugs = "https://github.com/kunifujiwara/voxcity/issues"
changelog = "https://github.com/kunifujiwara/voxcity/blob/master/changelog.md"
homepage = "https://github.com/kunifujiwara/voxcity"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["voxcity", "voxcity.download", "voxcity.geo", "voxcity.file", "voxcity.sim", "voxcity.utils"]

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.mypy]
files = "."
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"