[tool.poetry]
name = "voxelcity"
version = "0.1.68"
description = "voxelcity is an easy and one-stop tool to output 3d city models for microclimate simulation by integrating multiple geospatial open-data"
readme = "README.rst"
authors = ["Kunihiko Fujiwara <kunihiko@nus.edu.sg>"]
maintainers = ["Kunihiko Fujiwara <kunihiko@nus.edu.sg>"]
license = "MIT"
packages = [
    { include = "voxelcity", from = "src" }
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kunifujiwara/voxelcity/issues"
"Changelog" = "https://github.com/kunifujiwara/voxelcity/blob/master/changelog.md"
"Homepage" = "https://github.com/kunifujiwara/voxelcity"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "*"
typer = "*"
pandas = "*"
requests = "*"
pyproj = "*"
ipyleaflet = "*"
geopandas = "*"
rasterio = "*"
shapely = "*"
matplotlib = "*"
contextily = "*"
fiona = "*"
rtree = "*"
plotly = "*"
tqdm = "*"
scipy = "*"
affine = "*"
earthengine-api = "*"
geemap = "*"
rio-cogeo = "*"
geopy = "*"
py-vox-io = "*"
mapbox_vector_tile = "<=1.2.1"
numba = "*"
reverse_geocoder = "*"
pycountry = "*"
osm2geojson = "*"
seaborn = "*"
overturemaps = "*"
protobuf = "<=3.20.3"
timezonefinder = "*"

[tool.poetry.group.dev.dependencies]
coverage = "*"
mypy = "*"
pytest = "*"
ruff = "*"
pytest-cov = "^6.0.0"

[tool.poetry.scripts]
voxelcity = "voxelcity.cli:main"

[tool.mypy]
files = "."
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"